version: '3.7'
services:
  pinot:
    image: apachepinot/pinot:0.7.1
    command: "QuickStart -type batch"
    container_name: "pinot"
    ports:
      - "9000:9000"      
      - "8000:8000"

networks:
  default:
    external:
      name: pinot_bridge

# docker network create -d bridge pinot_bridge

# docker exec -it pinot bin/pinot-admin.sh AddTable \
#   -tableConfigFile /config/table.json \
#   -schemaFile /config/schema.json -exec