version: '3.7'
services:
  pinot:
    image: apachepinot/pinot:latest-jdk11
    networks:
      - broker-kafka-pinot
    command: "QuickStart -type hybrid"
    container_name: "pinot"
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ./pinot-docker-demo/pinot/config:/config

networks:
  broker-kafka-pinot:
    driver: bridge
